export interface Title {
  id: string;
  name: string;
  price: number;
  category: 'legendary' | 'epic' | 'rare' | 'uncommon' | 'common';
  description: string;
}

export const TITLE_CATALOG: Title[] = [
  // LEGENDARY TITLES (250-500 coins)
  { id: 'leg_001', name: 'The Unstoppable', price: 500, category: 'legendary', description: 'Nothing can break your will' },
  { id: 'leg_002', name: 'Supreme Commander', price: 500, category: 'legendary', description: 'Lead from the front' },
  { id: 'leg_003', name: 'Iron Colossus', price: 475, category: 'legendary', description: 'An unmovable force' },
  { id: 'leg_004', name: 'Phoenix Rising', price: 475, category: 'legendary', description: 'Born from the ashes' },
  { id: 'leg_005', name: 'Apex Predator', price: 450, category: 'legendary', description: 'Top of the food chain' },
  { id: 'leg_006', name: 'Living Legend', price: 450, category: 'legendary', description: 'Stories told about you' },
  { id: 'leg_007', name: 'Infinity Warrior', price: 425, category: 'legendary', description: 'Endless strength' },
  { id: 'leg_008', name: 'The Invincible', price: 425, category: 'legendary', description: 'Never defeated' },
  { id: 'leg_009', name: 'Storm Breaker', price: 400, category: 'legendary', description: 'Shatter all obstacles' },
  { id: 'leg_010', name: 'Alpha Prime', price: 400, category: 'legendary', description: 'First among equals' },
  { id: 'leg_011', name: 'Eternal Champion', price: 375, category: 'legendary', description: 'Forever victorious' },
  { id: 'leg_012', name: 'Omega Force', price: 375, category: 'legendary', description: 'The final power' },
  { id: 'leg_013', name: 'Titan Slayer', price: 350, category: 'legendary', description: 'Giant killer' },
  { id: 'leg_014', name: 'Diamond Fist', price: 350, category: 'legendary', description: 'Unbreakable strike' },
  { id: 'leg_015', name: 'Glory Seeker', price: 325, category: 'legendary', description: 'Chasing greatness' },
  { id: 'leg_016', name: 'War Machine', price: 325, category: 'legendary', description: 'Built for battle' },
  { id: 'leg_017', name: 'The Relentless', price: 300, category: 'legendary', description: 'Never gives up' },
  { id: 'leg_018', name: 'Beast Mode', price: 300, category: 'legendary', description: 'Unleash the animal' },
  { id: 'leg_019', name: 'Soul Crusher', price: 275, category: 'legendary', description: 'Break their spirit' },
  { id: 'leg_020', name: 'Iron Emperor', price: 275, category: 'legendary', description: 'Rule with strength' },
  { id: 'leg_021', name: 'Thunder God', price: 250, category: 'legendary', description: 'Wrath from above' },
  { id: 'leg_022', name: 'Blood Diamond', price: 250, category: 'legendary', description: 'Forged in combat' },
  { id: 'leg_023', name: 'Nightmare Fuel', price: 250, category: 'legendary', description: 'Fear incarnate' },
  { id: 'leg_024', name: 'The Destroyer', price: 250, category: 'legendary', description: 'Leave nothing standing' },
  { id: 'leg_025', name: 'Death Dealer', price: 250, category: 'legendary', description: 'Final judgment' },

  // EPIC TITLES (150-245 coins)
  { id: 'epic_001', name: 'Battle Tested', price: 225, category: 'epic', description: 'Proven in combat' },
  { id: 'epic_002', name: 'Iron Giant', price: 225, category: 'epic', description: 'Size and strength combined' },
  { id: 'epic_003', name: 'Savage Warrior', price: 210, category: 'epic', description: 'Primal strength' },
  { id: 'epic_004', name: 'Crimson Blade', price: 210, category: 'epic', description: 'Sharp and deadly' },
  { id: 'epic_005', name: 'Steel Sentinel', price: 200, category: 'epic', description: 'Guardian of iron' },
  { id: 'epic_006', name: 'Vengeance Seeker', price: 200, category: 'epic', description: 'Never forget' },
  { id: 'epic_007', name: 'Shadow Assassin', price: 190, category: 'epic', description: 'Strike from darkness' },
  { id: 'epic_008', name: 'Platinum Warrior', price: 190, category: 'epic', description: 'Refined excellence' },
  { id: 'epic_009', name: 'Chaos Bringer', price: 180, category: 'epic', description: 'Disorder and destruction' },
  { id: 'epic_010', name: 'Fury Unleashed', price: 180, category: 'epic', description: 'Rage personified' },
  { id: 'epic_011', name: 'Dragon Heart', price: 175, category: 'epic', description: 'Fire within' },
  { id: 'epic_012', name: 'Obsidian Knight', price: 175, category: 'epic', description: 'Dark protector' },
  { id: 'epic_013', name: 'Warlord Supreme', price: 170, category: 'epic', description: 'Master tactician' },
  { id: 'epic_014', name: 'Berserker King', price: 170, category: 'epic', description: 'Controlled chaos' },
  { id: 'epic_015', name: 'Pain Bringer', price: 165, category: 'epic', description: 'Suffering delivered' },
  { id: 'epic_016', name: 'Wolf Alpha', price: 165, category: 'epic', description: 'Pack leader' },
  { id: 'epic_017', name: 'Skull Crusher', price: 160, category: 'epic', description: 'Bone breaking power' },
  { id: 'epic_018', name: 'Venom Strike', price: 160, category: 'epic', description: 'Poisonous precision' },
  { id: 'epic_019', name: 'Phantom Menace', price: 155, category: 'epic', description: 'Unseen threat' },
  { id: 'epic_020', name: 'Savage Beast', price: 155, category: 'epic', description: 'Untamed ferocity' },
  { id: 'epic_021', name: 'Iron Fang', price: 150, category: 'epic', description: 'Bite of steel' },
  { id: 'epic_022', name: 'Thunder Strike', price: 150, category: 'epic', description: 'Lightning fast' },
  { id: 'epic_023', name: 'Dark Champion', price: 150, category: 'epic', description: 'Victory at any cost' },
  { id: 'epic_024', name: 'Rage Incarnate', price: 150, category: 'epic', description: 'Anger made flesh' },
  { id: 'epic_025', name: 'Doom Bringer', price: 150, category: 'epic', description: 'Herald of destruction' },
  { id: 'epic_026', name: 'Steel Typhoon', price: 150, category: 'epic', description: 'Unstoppable storm' },
  { id: 'epic_027', name: 'Ghost Striker', price: 150, category: 'epic', description: 'Invisible assault' },
  { id: 'epic_028', name: 'Blood Moon', price: 150, category: 'epic', description: 'Ominous power' },
  { id: 'epic_029', name: 'Viper Elite', price: 150, category: 'epic', description: 'Deadly precision' },
  { id: 'epic_030', name: 'War Hammer', price: 150, category: 'epic', description: 'Crushing force' },

  // RARE TITLES (100-145 coins)
  { id: 'rare_001', name: 'Battle Hardened', price: 140, category: 'rare', description: 'Forged in war' },
  { id: 'rare_002', name: 'Iron Resolve', price: 140, category: 'rare', description: 'Unshakeable will' },
  { id: 'rare_003', name: 'Combat Elite', price: 130, category: 'rare', description: 'Top tier fighter' },
  { id: 'rare_004', name: 'Savage Hunter', price: 130, category: 'rare', description: 'Predatory instinct' },
  { id: 'rare_005', name: 'Steel Enforcer', price: 125, category: 'rare', description: 'Law of iron' },
  { id: 'rare_006', name: 'Shadow Walker', price: 125, category: 'rare', description: 'Move unseen' },
  { id: 'rare_007', name: 'Tempest Fury', price: 120, category: 'rare', description: 'Storm of rage' },
  { id: 'rare_008', name: 'Vanguard Elite', price: 120, category: 'rare', description: 'Leading edge' },
  { id: 'rare_009', name: 'Crimson Warrior', price: 115, category: 'rare', description: 'Blood and glory' },
  { id: 'rare_010', name: 'Bronze Titan', price: 115, category: 'rare', description: 'Ancient strength' },
  { id: 'rare_011', name: 'Apex Hunter', price: 110, category: 'rare', description: 'Ultimate predator' },
  { id: 'rare_012', name: 'Storm Rider', price: 110, category: 'rare', description: 'Master of chaos' },
  { id: 'rare_013', name: 'Pain Train', price: 105, category: 'rare', description: 'Non-stop punishment' },
  { id: 'rare_014', name: 'Iron Juggernaut', price: 105, category: 'rare', description: 'Unstoppable momentum' },
  { id: 'rare_015', name: 'Blade Master', price: 100, category: 'rare', description: 'Sword virtuoso' },
  { id: 'rare_016', name: 'Fury Fighter', price: 100, category: 'rare', description: 'Angry excellence' },
  { id: 'rare_017', name: 'Wolf Pack', price: 100, category: 'rare', description: 'Strength in numbers' },
  { id: 'rare_018', name: 'Dark Soldier', price: 100, category: 'rare', description: 'Shadow warrior' },
  { id: 'rare_019', name: 'Savage Force', price: 100, category: 'rare', description: 'Brutal power' },
  { id: 'rare_020', name: 'Thunder Fist', price: 100, category: 'rare', description: 'Explosive punch' },
  { id: 'rare_021', name: 'Steel Guardian', price: 100, category: 'rare', description: 'Iron defender' },
  { id: 'rare_022', name: 'Crimson Tiger', price: 100, category: 'rare', description: 'Fierce predator' },
  { id: 'rare_023', name: 'Night Stalker', price: 100, category: 'rare', description: 'Darkness hunter' },
  { id: 'rare_024', name: 'Bone Breaker', price: 100, category: 'rare', description: 'Structural damage' },
  { id: 'rare_025', name: 'War Dog', price: 100, category: 'rare', description: 'Loyal fighter' },
  { id: 'rare_026', name: 'Iron Wolf', price: 100, category: 'rare', description: 'Metal predator' },
  { id: 'rare_027', name: 'Blood Hawk', price: 100, category: 'rare', description: 'Aerial assassin' },
  { id: 'rare_028', name: 'Storm Bringer', price: 100, category: 'rare', description: 'Chaos dealer' },
  { id: 'rare_029', name: 'Shadow Blade', price: 100, category: 'rare', description: 'Dark edge' },
  { id: 'rare_030', name: 'Rage Warrior', price: 100, category: 'rare', description: 'Controlled anger' },
  { id: 'rare_031', name: 'Venom Fang', price: 100, category: 'rare', description: 'Toxic bite' },
  { id: 'rare_032', name: 'Steel Claw', price: 100, category: 'rare', description: 'Metal grip' },
  { id: 'rare_033', name: 'Dark Phoenix', price: 100, category: 'rare', description: 'Reborn stronger' },
  { id: 'rare_034', name: 'Iron Eagle', price: 100, category: 'rare', description: 'Soaring strength' },
  { id: 'rare_035', name: 'Blood Knight', price: 100, category: 'rare', description: 'Crimson champion' },

  // UNCOMMON TITLES (50-95 coins)
  { id: 'unc_001', name: 'The Grinder', price: 90, category: 'uncommon', description: 'Work never stops' },
  { id: 'unc_002', name: 'Iron Veteran', price: 90, category: 'uncommon', description: 'Battle scarred' },
  { id: 'unc_003', name: 'Daily Driver', price: 80, category: 'uncommon', description: 'Consistent effort' },
  { id: 'unc_004', name: 'Power House', price: 80, category: 'uncommon', description: 'Raw strength' },
  { id: 'unc_005', name: 'Steel Worker', price: 75, category: 'uncommon', description: 'Built by labor' },
  { id: 'unc_006', name: 'Brave Heart', price: 75, category: 'uncommon', description: 'Courageous spirit' },
  { id: 'unc_007', name: 'Night Owl', price: 70, category: 'uncommon', description: 'Late night warrior' },
  { id: 'unc_008', name: 'Early Bird', price: 70, category: 'uncommon', description: 'Morning champion' },
  { id: 'unc_009', name: 'The Hustler', price: 65, category: 'uncommon', description: 'Never stop moving' },
  { id: 'unc_010', name: 'Gym Rat', price: 65, category: 'uncommon', description: 'Always training' },
  { id: 'unc_011', name: 'Iron Maiden', price: 60, category: 'uncommon', description: 'Tough as nails' },
  { id: 'unc_012', name: 'The Machine', price: 60, category: 'uncommon', description: 'Mechanical precision' },
  { id: 'unc_013', name: 'Comeback Kid', price: 55, category: 'uncommon', description: 'Never stays down' },
  { id: 'unc_014', name: 'Lucky Strike', price: 55, category: 'uncommon', description: 'Fortune favors you' },
  { id: 'unc_015', name: 'Iron Heart', price: 50, category: 'uncommon', description: 'Core of steel' },
  { id: 'unc_016', name: 'Road Warrior', price: 50, category: 'uncommon', description: 'Always moving' },
  { id: 'unc_017', name: 'Fire Starter', price: 50, category: 'uncommon', description: 'Ignite the flame' },
  { id: 'unc_018', name: 'Storm Chaser', price: 50, category: 'uncommon', description: 'Seeking chaos' },
  { id: 'unc_019', name: 'Steel Nerves', price: 50, category: 'uncommon', description: 'Unshakeable calm' },
  { id: 'unc_020', name: 'Rock Solid', price: 50, category: 'uncommon', description: 'Dependable strength' },
  { id: 'unc_021', name: 'Heavy Hitter', price: 50, category: 'uncommon', description: 'Big impact' },
  { id: 'unc_022', name: 'Quick Strike', price: 50, category: 'uncommon', description: 'Fast action' },
  { id: 'unc_023', name: 'Power Player', price: 50, category: 'uncommon', description: 'Influential force' },
  { id: 'unc_024', name: 'Iron Fist', price: 50, category: 'uncommon', description: 'Strong grip' },
  { id: 'unc_025', name: 'Brave Soul', price: 50, category: 'uncommon', description: 'Fearless spirit' },
  { id: 'unc_026', name: 'Night Fighter', price: 50, category: 'uncommon', description: 'Dark hours warrior' },
  { id: 'unc_027', name: 'Day Walker', price: 50, category: 'uncommon', description: 'Sunlight champion' },
  { id: 'unc_028', name: 'Steel Mind', price: 50, category: 'uncommon', description: 'Mental fortitude' },
  { id: 'unc_029', name: 'Iron Will', price: 50, category: 'uncommon', description: 'Unbreakable determination' },
  { id: 'unc_030', name: 'Storm Born', price: 50, category: 'uncommon', description: 'Chaos native' },
  { id: 'unc_031', name: 'Fire Heart', price: 50, category: 'uncommon', description: 'Burning passion' },
  { id: 'unc_032', name: 'Stone Wall', price: 50, category: 'uncommon', description: 'Immovable defense' },
  { id: 'unc_033', name: 'Swift Shadow', price: 50, category: 'uncommon', description: 'Quick darkness' },
  { id: 'unc_034', name: 'Lone Wolf', price: 50, category: 'uncommon', description: 'Solo strength' },
  { id: 'unc_035', name: 'War Horse', price: 50, category: 'uncommon', description: 'Battle ready' },
  { id: 'unc_036', name: 'Iron Lion', price: 50, category: 'uncommon', description: 'Metal king' },
  { id: 'unc_037', name: 'Blood Hound', price: 50, category: 'uncommon', description: 'Relentless tracker' },
  { id: 'unc_038', name: 'Dark Horse', price: 50, category: 'uncommon', description: 'Unexpected winner' },
  { id: 'unc_039', name: 'Steel Dragon', price: 50, category: 'uncommon', description: 'Metal beast' },
  { id: 'unc_040', name: 'Fire Fox', price: 50, category: 'uncommon', description: 'Clever flame' },

  // COMMON TITLES (25-45 coins)
  { id: 'com_001', name: 'The Dedicated', price: 45, category: 'common', description: 'Committed to the cause' },
  { id: 'com_002', name: 'The Consistent', price: 45, category: 'common', description: 'Steady progress' },
  { id: 'com_003', name: 'Go Getter', price: 40, category: 'common', description: 'Always chasing goals' },
  { id: 'com_004', name: 'Hard Worker', price: 40, category: 'common', description: 'Effort pays off' },
  { id: 'com_005', name: 'The Motivated', price: 35, category: 'common', description: 'Driven to succeed' },
  { id: 'com_006', name: 'Rising Star', price: 35, category: 'common', description: 'On the way up' },
  { id: 'com_007', name: 'The Determined', price: 30, category: 'common', description: 'Won\'t give up' },
  { id: 'com_008', name: 'Team Player', price: 30, category: 'common', description: 'Together we rise' },
  { id: 'com_009', name: 'The Focused', price: 25, category: 'common', description: 'Eyes on the prize' },
  { id: 'com_010', name: 'Gym Hero', price: 25, category: 'common', description: 'Regular attendee' },
  { id: 'com_011', name: 'The Persistent', price: 25, category: 'common', description: 'Keep pushing' },
  { id: 'com_012', name: 'Fitness Fan', price: 25, category: 'common', description: 'Love the grind' },
  { id: 'com_013', name: 'The Active', price: 25, category: 'common', description: 'Always moving' },
  { id: 'com_014', name: 'Goal Setter', price: 25, category: 'common', description: 'Plan and execute' },
  { id: 'com_015', name: 'The Strong', price: 25, category: 'common', description: 'Physical power' },
  { id: 'com_016', name: 'Push-Up Pro', price: 25, category: 'common', description: 'Master the basics' },
  { id: 'com_017', name: 'The Builder', price: 25, category: 'common', description: 'Construct strength' },
  { id: 'com_018', name: 'Morning Warrior', price: 25, category: 'common', description: 'Start strong' },
  { id: 'com_019', name: 'Night Grinder', price: 25, category: 'common', description: 'Work late' },
  { id: 'com_020', name: 'The Challenger', price: 25, category: 'common', description: 'Test limits' },
  { id: 'com_021', name: 'Streak Keeper', price: 25, category: 'common', description: 'Maintain momentum' },
  { id: 'com_022', name: 'The Believer', price: 25, category: 'common', description: 'Faith in yourself' },
  { id: 'com_023', name: 'Progress Maker', price: 25, category: 'common', description: 'Forward motion' },
  { id: 'com_024', name: 'The Capable', price: 25, category: 'common', description: 'You can do it' },
  { id: 'com_025', name: 'Gym Warrior', price: 25, category: 'common', description: 'Battle ready' },
  { id: 'com_026', name: 'The Achiever', price: 25, category: 'common', description: 'Get things done' },
  { id: 'com_027', name: 'Strength Seeker', price: 25, category: 'common', description: 'Quest for power' },
  { id: 'com_028', name: 'The Regular', price: 25, category: 'common', description: 'Reliable presence' },
  { id: 'com_029', name: 'Fitness First', price: 25, category: 'common', description: 'Health priority' },
  { id: 'com_030', name: 'The Committed', price: 25, category: 'common', description: 'All in' },
  { id: 'com_031', name: 'Daily Doer', price: 25, category: 'common', description: 'Every day counts' },
  { id: 'com_032', name: 'The Starter', price: 25, category: 'common', description: 'Begin the journey' },
  { id: 'com_033', name: 'Fitness Newbie', price: 25, category: 'common', description: 'Everyone starts somewhere' },
  { id: 'com_034', name: 'The Learner', price: 25, category: 'common', description: 'Always improving' },
  { id: 'com_035', name: 'Gym Novice', price: 25, category: 'common', description: 'Fresh start' },
  { id: 'com_036', name: 'The Hopeful', price: 25, category: 'common', description: 'Positive outlook' },
  { id: 'com_037', name: 'Strength Trainee', price: 25, category: 'common', description: 'Building power' },
  { id: 'com_038', name: 'The Eager', price: 25, category: 'common', description: 'Ready to work' },
  { id: 'com_039', name: 'Push-Up Pupil', price: 25, category: 'common', description: 'Learning the craft' },
  { id: 'com_040', name: 'The Brave', price: 25, category: 'common', description: 'Courage to try' },
  { id: 'com_041', name: 'Fitness Fighter', price: 25, category: 'common', description: 'Battle for health' },
  { id: 'com_042', name: 'The Resilient', price: 25, category: 'common', description: 'Bounce back' },
  { id: 'com_043', name: 'Gym Goer', price: 25, category: 'common', description: 'Show up' },
  { id: 'com_044', name: 'The Patient', price: 25, category: 'common', description: 'Good things take time' },
  { id: 'com_045', name: 'Strength Student', price: 25, category: 'common', description: 'Still learning' },
  { id: 'com_046', name: 'The Willing', price: 25, category: 'common', description: 'Ready to commit' },
  { id: 'com_047', name: 'Push-Up Pal', price: 25, category: 'common', description: 'Friendly competitor' },
  { id: 'com_048', name: 'The Trying', price: 25, category: 'common', description: 'Effort matters' },
  { id: 'com_049', name: 'Fitness Friend', price: 25, category: 'common', description: 'Support network' },
  { id: 'com_050', name: 'The Beginner', price: 25, category: 'common', description: 'First steps' },
  { id: 'com_051', name: 'Gym Member', price: 25, category: 'common', description: 'Part of the club' },
  { id: 'com_052', name: 'The Aspiring', price: 25, category: 'common', description: 'Dream big' },
  { id: 'com_053', name: 'Strength Seeker', price: 25, category: 'common', description: 'On the hunt' },
  { id: 'com_054', name: 'The Starter', price: 25, category: 'common', description: 'Day one' },
  { id: 'com_055', name: 'Push-Up Person', price: 25, category: 'common', description: 'Doing the work' },
  { id: 'com_056', name: 'The New', price: 25, category: 'common', description: 'Fresh blood' },
  { id: 'com_057', name: 'Fitness Follower', price: 25, category: 'common', description: 'On the path' },
  { id: 'com_058', name: 'The Growing', price: 25, category: 'common', description: 'Getting stronger' },
  { id: 'com_059', name: 'Gym Attendee', price: 25, category: 'common', description: 'Present and accounted for' },
  { id: 'com_060', name: 'The Developing', price: 25, category: 'common', description: 'Work in progress' },
  { id: 'com_061', name: 'Strength Builder', price: 25, category: 'common', description: 'Laying foundation' },
  { id: 'com_062', name: 'The Improving', price: 25, category: 'common', description: 'Better every day' },
  { id: 'com_063', name: 'Push-Up Enthusiast', price: 25, category: 'common', description: 'Love the exercise' },
  { id: 'com_064', name: 'The Advancing', price: 25, category: 'common', description: 'Moving forward' },
  { id: 'com_065', name: 'Fitness Participant', price: 25, category: 'common', description: 'In the game' },
  { id: 'com_066', name: 'The Progressing', price: 25, category: 'common', description: 'Making gains' },
  { id: 'com_067', name: 'Gym Visitor', price: 25, category: 'common', description: 'Stopping by' },
  { id: 'com_068', name: 'The Upcoming', price: 25, category: 'common', description: 'Watch this space' },
  { id: 'com_069', name: 'Strength Apprentice', price: 25, category: 'common', description: 'Under training' },
  { id: 'com_070', name: 'The Emerging', price: 25, category: 'common', description: 'Coming up' },
  { id: 'com_071', name: 'Push-Up Practitioner', price: 25, category: 'common', description: 'Practice makes perfect' },
  { id: 'com_072', name: 'The Evolving', price: 25, category: 'common', description: 'Constant change' },
  { id: 'com_073', name: 'Fitness Explorer', price: 25, category: 'common', description: 'Discovering strength' },
  { id: 'com_074', name: 'The Transforming', price: 25, category: 'common', description: 'Becoming better' },
  { id: 'com_075', name: 'Gym Regular', price: 25, category: 'common', description: 'Familiar face' },
  { id: 'com_076', name: 'The Changing', price: 25, category: 'common', description: 'New you' },
  { id: 'com_077', name: 'Strength Cultivator', price: 25, category: 'common', description: 'Growing power' },
  { id: 'com_078', name: 'The Rising', price: 25, category: 'common', description: 'Upward trajectory' },
  { id: 'com_079', name: 'Push-Up Partner', price: 25, category: 'common', description: 'Team effort' },
  { id: 'com_080', name: 'The Climbing', price: 25, category: 'common', description: 'Scaling heights' },
  { id: 'com_081', name: 'Fitness Journeyer', price: 25, category: 'common', description: 'Long road ahead' },
  { id: 'com_082', name: 'The Ascending', price: 25, category: 'common', description: 'Going up' },
  { id: 'com_083', name: 'Gym Companion', price: 25, category: 'common', description: 'Workout buddy' },
  { id: 'com_084', name: 'The Striving', price: 25, category: 'common', description: 'Reaching for more' },
  { id: 'com_085', name: 'Strength Enthusiast', price: 25, category: 'common', description: 'Passionate about power' },
  { id: 'com_086', name: 'The Pushing', price: 25, category: 'common', description: 'Forward momentum' },
  { id: 'com_087', name: 'Push-Up Advocate', price: 25, category: 'common', description: 'Spread the word' },
  { id: 'com_088', name: 'The Pursuing', price: 25, category: 'common', description: 'After excellence' },
  { id: 'com_089', name: 'Fitness Advocate', price: 25, category: 'common', description: 'Champion of health' },
  { id: 'com_090', name: 'The Seeking', price: 25, category: 'common', description: 'Always searching' },
  { id: 'com_091', name: 'Gym Loyalist', price: 25, category: 'common', description: 'True to the cause' },
  { id: 'com_092', name: 'The Hunting', price: 25, category: 'common', description: 'Track down goals' },
  { id: 'com_093', name: 'Strength Supporter', price: 25, category: 'common', description: 'Back the movement' },
  { id: 'com_094', name: 'The Chasing', price: 25, category: 'common', description: 'Hot pursuit' },
  { id: 'com_095', name: 'Push-Up Champion', price: 25, category: 'common', description: 'Defend the form' },
  { id: 'com_096', name: 'The Following', price: 25, category: 'common', description: 'On the trail' },
  { id: 'com_097', name: 'Fitness Believer', price: 25, category: 'common', description: 'True faith' },
  { id: 'com_098', name: 'The Tracking', price: 25, category: 'common', description: 'Monitor progress' },
  { id: 'com_099', name: 'Gym Devotee', price: 25, category: 'common', description: 'Dedicated follower' },
  { id: 'com_100', name: 'The Watching', price: 25, category: 'common', description: 'Eyes on improvement' },
  { id: 'com_101', name: 'Strength Fanatic', price: 25, category: 'common', description: 'Obsessed with gains' },
  { id: 'com_102', name: 'The Observing', price: 25, category: 'common', description: 'Learn by watching' },
  { id: 'com_103', name: 'Push-Up Devotee', price: 25, category: 'common', description: 'Loyal to the exercise' },
  { id: 'com_104', name: 'The Monitoring', price: 25, category: 'common', description: 'Track everything' },
  { id: 'com_105', name: 'Fitness Disciple', price: 25, category: 'common', description: 'Follow the path' },
  { id: 'com_106', name: 'The Recording', price: 25, category: 'common', description: 'Document the journey' },
  { id: 'com_107', name: 'Gym Adherent', price: 25, category: 'common', description: 'Stick to it' },
  { id: 'com_108', name: 'The Noting', price: 25, category: 'common', description: 'Take note' },
  { id: 'com_109', name: 'Strength Adherent', price: 25, category: 'common', description: 'Follow strength' },
  { id: 'com_110', name: 'The Logging', price: 25, category: 'common', description: 'Keep records' },
];

export const getCategoryColor = (category: Title['category']): string => {
  switch (category) {
    case 'legendary':
      return 'text-warning border-warning bg-warning/10';
    case 'epic':
      return 'text-purple-400 border-purple-400 bg-purple-400/10';
    case 'rare':
      return 'text-electric-blue border-electric-blue bg-electric-blue/10';
    case 'uncommon':
      return 'text-success border-success bg-success/10';
    case 'common':
      return 'text-gray-400 border-gray-400 bg-gray-400/10';
  }
};

export const getCategoryLabel = (category: Title['category']): string => {
  return category.charAt(0).toUpperCase() + category.slice(1);
};
